# ADHDP configuration for LunarLander
type: "adhdp"

# Neural network architecture
actor_network:
  hidden_layers: [64, 32]
  activation: "tanh"
  learning_rate: 0.001
  
critic_network:
  hidden_layers: [64, 32] 
  activation: "tanh"
  learning_rate: 0.002
  
# ADHDP specific parameters
gamma: 0.99
tau: 0.001                   # Soft update rate
exploration_noise: 0.1

# Training parameters
batch_size: 64
memory_size: 100000
min_memory_size: 1000
update_frequency: 1