# IDHP configuration for LunarLander
type: idhp
hidden_sizes: [64, 64]
actor_lr: 0.0002
critic_lr: 0.0004
discount_factor: 0.99
initial_noise_std: 0.05
noise_decay: 0.999
min_noise_std: 0.01
device: 'cpu'
rls_lam: 0.99
rls_delta: 1.0