agent:
  type: ADHDP
  # training hyperparameters
  actor_lr: 0.005
  critic_lr: 0.005
  discount_factor: 0.99
  noise: False

  # architecture hyperparameters
  obs_dim: 2
  act_dim: 2
  hidden_dim: 32
  num_layers: 2

env:
  max_steps: 3000
  dt: 0.01
  state_indices_to_keep: [4] # Keep only the relevant states for observation
  reference_config:
    1:                      # the state index
      type: sin        # choose: 'sin', 'constant', or 'cos_step'
      amplitude:
        min: -0.349        # minimum amplitude (degrees for cos_step, radians for sin)
        max: 0.349          # maximum amplitude (degrees for cos_step, radians for sin)
        n_levels: 15      # number of discrete levels (for cos_step)
      step_duration: 
        min: 5.0            # minimum duration of each reference segment (seconds)
        max: 5.0        # maximum duration of each reference segment (seconds)
        n_levels: 1
      transition_duration:
        min: 3.0           # minimum duration of gap between segments (seconds)
        max: 5.0            # maximum duration of gap between segments (seconds)
        n_levels: 3
      
      # Parameters for sin
      A: 0.35               # amplitude in radians
      T: 5.0                # period
      phi: 0.0              # phase
      
      # Parameters for constant
      value: 1.0            # constant value
      
      # Parameters for cos_step
      amp_range: [-20.0, 20.0]  # amplitude limits in degrees
      n_levels: 15               # discrete amplitude levels
      T_step: 5.0                # step duration


  # Observation space bounds
  obs_low: [-1.5, -2.5]
  obs_high: [1.5, 2.5]

  # Action space bounds
  action_low: [0, -22.5]
  action_high: [0, 27]


training: 
  episodes: 10
  seed: 42
  
  milestones_fractions:
    - 0.0
    - 0.1
    - 0.2
    - 1.0
  
  checkpoint_interval: 10000
  resume_from: null  
  #resume_from: experiments\q_learning\pitch_rate_and_theta_error_obs\checkpoint_final_ep60100\checkpoint_ep60099_brain.npz # null OR .npz file path
  

eval:
  rolling_length: 1
  convergence_threshold: 0.05
  last_n: 50 #Number of final episodes to compute average and stability.
  settling_tolerance: 0.05
  settling_duration: 100 # Number of steps to consider for settling duration.

test:
  checkpoint_path: experiments\q_learning\pitch_rate_and_theta_error_obs\checkpoint_final_ep60100\checkpoint_ep60099_brain.npz # .npz file

