# Minimal test configuration for system validation
# Fast training with just a few episodes

agent:
  type: "ADHDP"
  obs_dim: 2
  act_dim: 2
  hidden_dim: 16
  num_layers: 2
  actor_lr: 0.01
  critic_lr: 0.01
  gamma: 0.99
  noise: true
  device: "cpu"

environment:
  name: "f16"
  max_steps: 100               # Short episodes for testing
  dt: 0.01
  state_indices_for_obs: [4]
  action_low: [0, -22.5]
  action_high: [0, 27.0]
  obs_low: [-1.5, -2.5]
  obs_high: [1.5, 2.5]
  reference_config:
    1:
      type: "sin"
      A: 0.35
      T: 5.0
      phi: 0.0

training:
  episodes: 5                  # Just 5 episodes for testing
  seed: 42
  log_frequency: 2
  detailed_logging: true

checkpointing:
  interval: 3                  # Checkpoint every 3 episodes
  keep_last_n: 2
  save_best: true
  resume_from: null

plotting:
  training_metrics:
    interval: 2                # Plot every 2 episodes
    rolling_window: 2
    save_individual: true
  trajectories:
    episodes: [1, 3, 5]        # Plot trajectories for episodes 1, 3, and 5
    save_data: true
  figure_size: [10, 6]
  dpi: 100
  style: "default"

evaluation:
  rolling_window: 3
  convergence_threshold: 0.1
  stability_episodes: 2